### ISSUE TITLE
sqlite3

### ISSUE THREAD

**Issue by kkk-alt** [Grigorich-JSDio/TG-Parser#2]
─(kali㉿kali)-[~/TG-Parser/data]
└─$ python3 main.py                                 
Введите ссылку на чат: https://t.me/cisspknights
Упс... Возникла ошибка
Текст ошибки:

unable to open database file

Отправьте скриншот разработчику.
Traceback (most recent call last):
  File "/home/kali/TG-Parser/data/main.py", line 134, in <module>
    raise e
  File "/home/kali/TG-Parser/data/main.py", line 27, in <module>
    res = loop.run_until_complete(check_chat(link, 'url'))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/kali/TG-Parser/data/my_functions.py", line 53, in check_chat
    async with TelegramClient('session', api_id, api_hash) as client:
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/telegrambaseclient.py", line 262, in __init__
    session = SQLiteSession(session)
  File "/usr/local/lib/python3.9/dist-packages/telethon/sessions/sqlite.py", line 47, in __init__
    c = self._cursor()
  File "/usr/local/lib/python3.9/dist-packages/telethon/sessions/sqlite.py", line 228, in _cursor
    self._conn = sqlite3.connect(self.filename,
sqlite3.OperationalError: unable to open database file

**Comment by Grigorich-JSDio** [comment]
Данная ошибка описана [тут](https://docs.telethon.dev/en/latest/quick-references/faq.html#sqlite3-operationalerror-database-is-locked). Проверьте, не удаляли ли вы файл сессии и не запущен ли у вас парралельно ещё один образец скрипта.
